# Generated by Django 6.0.1 on 2026-01-29 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], unique=True)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('default_video_url', models.URLField(blank=True)),
                ('default_video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('year', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(blank=True, max_length=255)),
                ('meta', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('youtube_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='media_slider.slider')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('slider', 'position')},
            },
        ),
        migrations.CreateModel(
            name='DSPLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsps', to='media_slider.slideritem')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
